# Generated by Django 2.2 on 2019-12-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191208_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('uncompleted', '未完了'), ('completed', '完了')], max_length=30),
        ),
    ]
